// <auto-generated />
using Labb_3___API.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb_3___API.Migrations
{
    [DbContext(typeof(PersonDbContext))]
    [Migration("20250503155957_Seeddata")]
    partial class Seeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb_3___API.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Spela och titta på fotboll",
                            Name = "Fotboll"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Spela gitarr och lyssna på musik",
                            Name = "Musik"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Utveckla applikationer och hemsidor",
                            Name = "Programmering"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Besöka nya länder och kulturer",
                            Name = "Resa"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Laga och njuta av god mat",
                            Name = "Matlagning"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Ta bilder och redigera dem",
                            Name = "Fotografi"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Hålla sig i form och träna",
                            Name = "Träning"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Läsa böcker och skriva",
                            Name = "Litteratur"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Titta på filmer och serier",
                            Name = "Film"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Spela datorspel och brädspel",
                            Name = "Spel"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Skapa och uppskatta konstverk",
                            Name = "Konst"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Vandra och njuta av naturen",
                            Name = "Natur"
                        });
                });

            modelBuilder.Entity("Labb_3___API.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestId = 1,
                            PersonId = 1,
                            Url = "https://www.fotbollskanalen.se/"
                        },
                        new
                        {
                            Id = 2,
                            InterestId = 2,
                            PersonId = 1,
                            Url = "https://open.spotify.com/"
                        },
                        new
                        {
                            Id = 3,
                            InterestId = 3,
                            PersonId = 2,
                            Url = "https://csharpskolan.se/borja-har/"
                        },
                        new
                        {
                            Id = 4,
                            InterestId = 4,
                            PersonId = 2,
                            Url = "https://www.trivago.se/"
                        },
                        new
                        {
                            Id = 5,
                            InterestId = 5,
                            PersonId = 3,
                            Url = "https://www.kitchenlab.se/k/matlagning/"
                        },
                        new
                        {
                            Id = 6,
                            InterestId = 6,
                            PersonId = 3,
                            Url = "https://www.gotaplatsensfoto.se/"
                        },
                        new
                        {
                            Id = 7,
                            InterestId = 2,
                            PersonId = 4,
                            Url = "https://tidal.com/"
                        },
                        new
                        {
                            Id = 8,
                            InterestId = 7,
                            PersonId = 4,
                            Url = "https://www.actic.se/"
                        },
                        new
                        {
                            Id = 9,
                            InterestId = 8,
                            PersonId = 5,
                            Url = "https://litteraturbanken.se/"
                        },
                        new
                        {
                            Id = 10,
                            InterestId = 9,
                            PersonId = 5,
                            Url = "https://www.netflix.com/se/"
                        },
                        new
                        {
                            Id = 11,
                            InterestId = 10,
                            PersonId = 6,
                            Url = "https://store.steampowered.com/"
                        },
                        new
                        {
                            Id = 12,
                            InterestId = 11,
                            PersonId = 6,
                            Url = "https://konst.se"
                        },
                        new
                        {
                            Id = 13,
                            InterestId = 12,
                            PersonId = 7,
                            Url = "https://www.sverigesnatur.org/"
                        },
                        new
                        {
                            Id = 14,
                            InterestId = 1,
                            PersonId = 7,
                            Url = "https://allsvenskan.se/"
                        },
                        new
                        {
                            Id = 15,
                            InterestId = 3,
                            PersonId = 8,
                            Url = "https://www.javascript.com/"
                        },
                        new
                        {
                            Id = 16,
                            InterestId = 5,
                            PersonId = 8,
                            Url = "https://www.gordonramsay.com/"
                        });
                });

            modelBuilder.Entity("Labb_3___API.Models.MtmInterest", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.HasKey("PersonId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("PersonInterests");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            InterestId = 1
                        },
                        new
                        {
                            PersonId = 1,
                            InterestId = 2
                        },
                        new
                        {
                            PersonId = 2,
                            InterestId = 3
                        },
                        new
                        {
                            PersonId = 2,
                            InterestId = 4
                        },
                        new
                        {
                            PersonId = 3,
                            InterestId = 5
                        },
                        new
                        {
                            PersonId = 3,
                            InterestId = 6
                        },
                        new
                        {
                            PersonId = 4,
                            InterestId = 2
                        },
                        new
                        {
                            PersonId = 4,
                            InterestId = 7
                        },
                        new
                        {
                            PersonId = 5,
                            InterestId = 8
                        },
                        new
                        {
                            PersonId = 5,
                            InterestId = 9
                        },
                        new
                        {
                            PersonId = 6,
                            InterestId = 10
                        },
                        new
                        {
                            PersonId = 6,
                            InterestId = 11
                        },
                        new
                        {
                            PersonId = 7,
                            InterestId = 12
                        },
                        new
                        {
                            PersonId = 7,
                            InterestId = 1
                        },
                        new
                        {
                            PersonId = 8,
                            InterestId = 3
                        },
                        new
                        {
                            PersonId = 8,
                            InterestId = 5
                        });
                });

            modelBuilder.Entity("Labb_3___API.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Anna Andersson",
                            Phone = "0701234567"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bertil Berg",
                            Phone = "0739876543"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cecilia Carlsson",
                            Phone = "0761122334"
                        },
                        new
                        {
                            Id = 4,
                            Name = "David Dahl",
                            Phone = "0709876543"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Eva Eriksson",
                            Phone = "0734567890"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fredrik Frisk",
                            Phone = "0765432109"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Gina Gustavsson",
                            Phone = "0701234567"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Henrik Hansson",
                            Phone = "0739876543"
                        });
                });

            modelBuilder.Entity("Labb_3___API.Models.Link", b =>
                {
                    b.HasOne("Labb_3___API.Models.Interest", "Interest")
                        .WithMany("Links")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb_3___API.Models.Person", "Person")
                        .WithMany("Links")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Labb_3___API.Models.MtmInterest", b =>
                {
                    b.HasOne("Labb_3___API.Models.Interest", "Interest")
                        .WithMany("PersonInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb_3___API.Models.Person", "Person")
                        .WithMany("PersonInterests")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Labb_3___API.Models.Interest", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("PersonInterests");
                });

            modelBuilder.Entity("Labb_3___API.Models.Person", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("PersonInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
